seed: 42

model:
  target: src.models.toy_model.ToyModel
  model_kwargs:
    key: value

  training_kwargs:
    optimizer:
      target: torch.optim.AdamW
      lr: 1e-4
    scheduler: cosine_schedule_with_warmup
    warmup_steps: 1000

trainer:
  max_epochs: 5

dataloader:
  batch_size: 32
  num_workers: 32
  pin_memory: True
  persistent_workers: True
