seed: 42
dataset_name: my_dataset


model:
  target: src.models.vanilla.VanillaModel
  model_kwargs:

  training_kwargs:
    lr: 1e-4
    warmup_steps: 1000


trainer:
  target: lightning.pytorch.trainer.Trainer
  devices: 
  max_epochs: 1
  max_steps: -1
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  logger:
    target: lightning.pytorch.loggers.wandb.WandbLogger
    project: 
    name: 
  num_sanity_val_steps: 2


dataloader:
  batch_size: 32
  num_workers: 32
  pin_memory: True
  persistent_workers: True
