seed: 42

model:
  target: src.models.vanilla.VanillaModel
  model_kwargs:
    hidden_size: 768

  training_kwargs:
    lr: 1e-4
    scheduler: cosine_schedule_with_warmup
    warmup_steps: 1000

dataloader:
  batch_size: 32
  num_workers: 32
  pin_memory: True
  persistent_workers: True
